vacation_spots = ['tokyo', 'pairs', 'austen', 'singapore', 'japan']
print(vacation_spots)
print(sorted(vacation_spots))
print(vacation_spots)
print(sorted(vacation_spots, reverse=True))
print(vacation_spots)
vacation_spots.sort(reverse=True)
print(vacation_spots)
vacation_spots.sort(reverse=False)
print(vacation_spots)
vacation_spots.sort()
print(vacation_spots)
vacation_spots.sort(reverse=True)
print(vacation_spots)